# -*- coding: utf-8 -*-
"""infrared_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMAVJBz-7iT5UMEYKmvxOGf7ipZyQU-L
"""

!pip install diffusers transformers accelerate controlnet_aux opencv-python pillow torch torchvision

import requests
import os

image_url = "https://media.istockphoto.com/id/517995089/photo/thermovision-image-on-house.jpg?s=612x612&w=0&k=20&c=9EGdYRvzqaGSkRE0U7U2Lih9Pj7Khs7rt-YcwRU_qDI="
image_filename = "downloaded_image.jpg"

try:
    response = requests.get(image_url)
    response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

    with open(image_filename, 'wb') as f:
        f.write(response.content)

    uploaded_image_path = image_filename
    print(f"Image successfully downloaded and saved as: {uploaded_image_path}")

except requests.exceptions.RequestException as e:
    print(f"Error downloading image: {e}")
    uploaded_image_path = None
    print("No image downloaded.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    uploaded_image_path = None
    print("No image downloaded.")

!pip install -q diffusers transformers accelerate controlnet_aux safetensors opencv-python pillow

import requests
import os

image_url = "https://media.istockphoto.com/id/517995089/photo/thermovision-image-on-house.jpg?s=612x612&w=0&k=20&c=9EGdYRvzqaGSkRE0U7U2Lih9Pj7Khs7rt-YcwRU_qDI="
image_filename = "downloaded_image.jpg"

try:
    response = requests.get(image_url)
    response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)

    with open(image_filename, 'wb') as f:
        f.write(response.content)

    uploaded_image_path = image_filename
    print(f"Image successfully downloaded and saved as: {uploaded_image_path}")

except requests.exceptions.RequestException as e:
    print(f"Error downloading image: {e}")
    uploaded_image_path = None
    print("No image downloaded.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
    uploaded_image_path = None
    print("No image downloaded.")

import os

if 'uploaded_image_path' in locals() and uploaded_image_path is not None:
    print(f"Selected image path: {uploaded_image_path}")
else:
    print("No image path has been set. Please upload an image using the previous cell.")

from PIL import Image
import matplotlib.pyplot as plt
import os

# Ensure 'uploaded_image_path' is defined from the upload cell
if 'uploaded_image_path' not in locals() or uploaded_image_path is None:
    raise ValueError("No image path found. Please run the upload cell above.")

image_path = uploaded_image_path

# Check if the image file exists before attempting to open it
if not os.path.exists(image_path):
    raise FileNotFoundError(f"The uploaded image '{image_path}' was not found. Please re-upload.")

img = Image.open(image_path)

plt.figure(figsize=(6,6))
plt.imshow(img, cmap="gray")
plt.axis("off")
plt.show()

print("Image size:", img.size)

import torch
from diffusers import StableDiffusionImg2ImgPipeline
from PIL import Image

pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

# Define a negative prompt
negative_prompt = "blurry, ugly, poor quality, low resolution, bad anatomy"

# Use the image loaded in the previous cell
init_image = img.convert("RGB")
init_image = init_image.resize((512, 512))

prompt = (
    "realistic daytime building photograph, natural colors, "
    "architectural details, blue sky, realistic lighting, high quality"
)

# Removed control_image and controlnet_conditioning_scale as they are not valid for StableDiffusionImg2ImgPipeline
result = pipe(
    prompt=prompt,
    negative_prompt=negative_prompt,
    image=init_image,
    num_inference_steps=50,
    guidance_scale=11,
).images[0]

result.save("/content/building_colorized_diffusion.png")

print("Saved: building_colorized_diffusion.png")

from PIL import Image
import matplotlib.pyplot as plt

# Updated image path to match the actual loaded file
orig = Image.open(image_path)
gen = Image.open("/content/building_colorized_diffusion.png")

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.imshow(orig, cmap="gray")
plt.title("Infrared Input")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(gen)
plt.title("Diffusion Output")
plt.axis("off")

plt.show()

"""### Generate a more accurate image using ControlNet"""

from controlnet_aux import CannyDetector
from diffusers import ControlNetModel, StableDiffusionControlNetPipeline
import numpy as np

# Load Canny edge detector (no arguments here)
canny_detector = CannyDetector()

# Convert PIL image to numpy array for Canny processing, using the 'img' from a previous cell
image_np = np.array(img.convert("RGB"))

# Apply Canny edge detection with adjusted thresholds
control_image = canny_detector(image_np, low_threshold=50, high_threshold=150)

# Display the control image
plt.figure(figsize=(6,6))
plt.imshow(control_image, cmap='gray')
plt.title('Canny Edge Map')
plt.axis('off')
plt.show()

print("Canny edge map generated.")

# Load ControlNet model
controlnet = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-canny",
    torch_dtype=torch.float16
).to("cuda")

# Create Stable Diffusion ControlNet Pipeline
controlnet_pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=controlnet,
    torch_dtype=torch.float16
).to("cuda")

# Ensure control_image is a single PIL Image object
# If control_image was a numpy array or a list, convert it to a single PIL.Image.Image.
if isinstance(control_image, np.ndarray):
    control_image = Image.fromarray(control_image)
elif isinstance(control_image, list):
    if len(control_image) > 0:
        print(f"DEBUG: control_image was a list of {len(control_image)} items. Attempting to use the first item as PIL Image.")
        # Try to convert if the item is a numpy array, otherwise assume it's already a PIL Image
        if isinstance(control_image[0], np.ndarray):
            control_image = Image.fromarray(control_image[0])
        elif isinstance(control_image[0], Image.Image):
            control_image = control_image[0]
        else:
            raise TypeError(f"List item in control_image is of unexpected type: {type(control_image[0])}. Cannot convert to PIL Image.")
    else:
        raise ValueError("control_image is an empty list, cannot proceed.")
elif not isinstance(control_image, Image.Image):
    raise TypeError(f"control_image is of unexpected type: {type(control_image)}. Expected PIL Image, numpy array, or list of these.")

# Updated prompt for clearer and more accurate output
prompt = ("""
Award-winning photograph of an ultra-realistic outdoor electrical substation at golden hour, vibrant natural colors, industrial equipment, weathered metal transformers, intricate power lines, photorealistic, sharp focus, dynamic lighting, highly detailed, 8k, HDR, masterpiece, epic composition.
""")

# Generate image with ControlNet with increased inference steps and higher conditioning scale
controlnet_result = controlnet_pipe(
    prompt=prompt,
    image=control_image,
    num_inference_steps=30, # Increased inference steps for better detail
    # Adjust controlnet_conditioning_scale to balance fidelity (higher value) and creativity (lower value)
    controlnet_conditioning_scale=1.2
).images[0]

file_name = "building_colorized_controlnet.png"
controlnet_result.save(file_name)

import os
if not os.path.exists(file_name):
    raise FileNotFoundError(f"Failed to save {file_name}. Please check execution.")

print(f"Saved: {file_name}")

from PIL import Image
import matplotlib.pyplot as plt
import os

# Updated image path to match the actual loaded file
orig = Image.open(image_path)

# Ensure using absolute path for the generated file
file_to_open = "/content/building_colorized_controlnet.png"
if os.path.exists(file_to_open):
    control_img_display = Image.open(file_to_open)
else:
    raise FileNotFoundError(f"Expected file '{file_to_open}' not found. Please ensure cell `9b2ac2a4` ran successfully and created this file.")

plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.imshow(orig, cmap="gray")
plt.title("Infrared Input")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(control_image, cmap="gray")
plt.title("Control Image (Canny Edges)")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(control_img_display)
plt.title("ControlNet Output")
plt.axis("off")

plt.show()

!pip install -q timm

from controlnet_aux import CannyDetector, MidasDetector
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

rgb_img = img.convert("RGB").resize((512,512))

image_np = np.array(rgb_img)

canny = CannyDetector()
depth = MidasDetector.from_pretrained("lllyasviel/Annotators")

canny_img = canny(
    image_np,
    low_threshold=100,
    high_threshold=200
)

depth_img = depth(rgb_img)

plt.figure(figsize=(12,5))

plt.subplot(121)
plt.imshow(canny_img,cmap="gray")
plt.title("Canny")

plt.subplot(122)
plt.imshow(depth_img)
plt.title("Depth")

plt.show()

import torch

from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetPipeline
)

controlnet_canny = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-canny",
    torch_dtype=torch.float16
)

controlnet_depth = ControlNetModel.from_pretrained(
    "lllyasviel/sd-controlnet-depth",
    torch_dtype=torch.float16
)

pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    controlnet=[
        controlnet_canny,
        controlnet_depth
    ],
    torch_dtype=torch.float16
).to("cuda")

pipe.enable_attention_slicing()

uploaded_image_path = "/content/downloaded_image.jpg"
print(f"uploaded_image_path defined as: {uploaded_image_path}")

from PIL import Image
from controlnet_aux import CannyDetector, MidasDetector
import numpy as np
import os

# Ensure 'uploaded_image_path' is defined. This variable is expected to be set by a previous cell.
if 'uploaded_image_path' not in locals() or uploaded_image_path is None:
    raise ValueError("The 'uploaded_image_path' is not defined. Please run the image download/upload cell first.")

# Load the image using the provided path
image_path = uploaded_image_path
if not os.path.exists(image_path):
    raise FileNotFoundError(f"The image '{image_path}' was not found. Please ensure it was downloaded/uploaded correctly.")

img = Image.open(image_path)

rgb_img = img.convert("RGB").resize((512,512))
image_np = np.array(rgb_img)

canny = CannyDetector()
depth = MidasDetector.from_pretrained("lllyasviel/Annotators")

canny_img = canny(
    image_np,
    low_threshold=100,
    high_threshold=200
)

depth_img = depth(rgb_img)

result = pipe(
    prompt="""
Ultra realistic residential house,
real world architecture,
natural wall colors,
clean windows,
realistic roof tiles,
blue sky,
green vegetation,
daylight,
photorealistic,
high detail,
sharp focus,
8k photography,
architectural photography,
real materials,
accurate perspective
""",
    negative_prompt="""
cartoon,
anime,
painting,
cgi,
substation,
transformer station,
industrial plant,
distorted,
blurry,
low quality,
oversaturated,
fog,
dark sky,
artifacts
""",

    image=[
        Image.fromarray(canny_img),
        depth_img
    ],

    num_inference_steps=50,

    guidance_scale=9.5,

    controlnet_conditioning_scale=[
        1.5,
        1.3
    ]
).images[0]

result.save(
    "/content/improved_colorized_result.png"
)

result

import matplotlib.pyplot as plt

if 'img' in locals():
    plt.figure(figsize=(6,6))
    plt.imshow(img)
    plt.title("Current 'img' variable")
    plt.axis("off")
    plt.show()
    print(f"Image size of 'img': {img.size}")
else:
    print("The 'img' variable is not defined.")

from PIL import ImageEnhance

img_out = Image.open(
    "/content/improved_colorized_result.png"
)

img_out = ImageEnhance.Color(
    img_out
).enhance(1.15)

img_out = ImageEnhance.Contrast(
    img_out
).enhance(1.10)

img_out.save(
    "/content/final_output.png"
)

import matplotlib.pyplot as plt
from PIL import Image

orig = img.convert("RGB")

final = Image.open(
    "/content/final_output.png"
)

plt.figure(figsize=(14,6))

plt.subplot(121)
plt.imshow(orig)
plt.title("Infrared Input")
plt.axis("off")

plt.subplot(122)
plt.imshow(final)
plt.title("Improved Output")
plt.axis("off")

plt.show()